from typing import Literal

licenseTypeSchema = Literal['CREATOR_MUSIC_LICENSE_TYPE_YOUTUBE', 'CREATOR_MUSIC_LICENSE_TYPE_CCBY_4']

genreSchema = Literal['CREATOR_MUSIC_GENRE_ROCK', 'CREATOR_MUSIC_GENRE_RNB_AND_SOUL', 'CREATOR_MUSIC_GENRE_CLASSICAL', 'CREATOR_MUSIC_GENRE_AMBIENT', 'CREATOR_MUSIC_GENRE_POP', 'CREATOR_MUSIC_GENRE_ALTERNATIVE_AND_PUNK', 'CREATOR_MUSIC_GENRE_JAZZ_AND_BLUES', 'CREATOR_MUSIC_GENRE_HOLIDAY', 'CREATOR_MUSIC_GENRE_COUNTRY_AND_FOLK', 'CREATOR_MUSIC_GENRE_CHILDRENS', 'CREATOR_MUSIC_GENRE_REGGAE', 'CREATOR_MUSIC_GENRE_CINEMATIC', 'CREATOR_MUSIC_GENRE_DANCE_AND_ELECTRONICS', 'CREATOR_MUSIC_GENRE_HIP_HOP_AND_RAP']

moodSchema = Literal['CREATOR_MUSIC_MOOD_FUNKY', 'CREATOR_MUSIC_MOOD_INSPIRATIONAL', 'CREATOR_MUSIC_MOOD_HAPPY', 'CREATOR_MUSIC_MOOD_SAD', 'CREATOR_MUSIC_MOOD_DARK', 'CREATOR_MUSIC_MOOD_ANGRY', 'CREATOR_MUSIC_MOOD_BRIGHT', 'CREATOR_MUSIC_MOOD_DRAMATIC', 'CREATOR_MUSIC_MOOD_CALM', 'CREATOR_MUSIC_MOOD_ROMANTIC']

instrumentSchema = Literal['CREATOR_MUSIC_INSTRUMENT_TRUMPET', 'CREATOR_MUSIC_INSTRUMENT_SYNTH', 'CREATOR_MUSIC_INSTRUMENT_ELECTRIC_GUITAR', 'CREATOR_MUSIC_INSTRUMENT_ORGAN', 'CREATOR_MUSIC_INSTRUMENT_DRUMS', 'CREATOR_MUSIC_INSTRUMENT_ACOUSTIC_GUITAR', 'CREATOR_MUSIC_INSTRUMENT_STRINGS', 'CREATOR_MUSIC_INSTRUMENT_BASS', 'CREATOR_MUSIC_INSTRUMENT_PIANO']
